name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [17.x]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: npm install
      - name: Build production
        run: npm run build:prod
        if: always()
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting styles
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()
      - name: Build storybook static files
        run: npm run storybook:build
        if: always()
      - name: Screenshot testing
        run: npm run test:ui:ci
        if: always()