name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1