name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [17.x]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: npm install
      - name: Build production
        run: npm run build:prod
      - name: Linting typescript
        run: npm run lint:ts
      - name: Linting styles
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit